name: Build and Push to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: amcui-grademanager
          addLatest: true
          registry: ghcr.io
          # githubOrg: override-org # optional
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          buildArgs: |
            VITE_COMMITHASH=${{ github.sha }}
